<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Haiku-bugs] [Haiku] #3354: f.seekable() fails in python	test_fileio.py
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/haiku-bugs/2009-January/index.html" >
   <LINK REL="made" HREF="mailto:haiku-bugs%40lists.berlios.de?Subject=Re%3A%20%5BHaiku-bugs%5D%20%5BHaiku%5D%20%233354%3A%20f.seekable%28%29%20fails%20in%20python%0A%09test_fileio.py&In-Reply-To=%3C042.02607e968f9ace961359cf269d1c058b%40haiku-os.org%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="013909.html">
   <LINK REL="Next"  HREF="013911.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Haiku-bugs] [Haiku] #3354: f.seekable() fails in python	test_fileio.py</H1>
    <B>scottmc</B> 
    <A HREF="mailto:haiku-bugs%40lists.berlios.de?Subject=Re%3A%20%5BHaiku-bugs%5D%20%5BHaiku%5D%20%233354%3A%20f.seekable%28%29%20fails%20in%20python%0A%09test_fileio.py&In-Reply-To=%3C042.02607e968f9ace961359cf269d1c058b%40haiku-os.org%3E"
       TITLE="[Haiku-bugs] [Haiku] #3354: f.seekable() fails in python	test_fileio.py">trac at haiku-os.org
       </A><BR>
    <I>Fri Jan 23 06:55:24 CET 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="013909.html">[Haiku-bugs] [Haiku] #3353: resource.h broken (not implemented yet?)
</A></li>
        <LI>Next message: <A HREF="013911.html">[Haiku-bugs] [Haiku] #3355: using mv to move a folder onto itself	should fail
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13910">[ date ]</a>
              <a href="thread.html#13910">[ thread ]</a>
              <a href="subject.html#13910">[ subject ]</a>
              <a href="author.html#13910">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>#3354: f.seekable() fails in python test_fileio.py
-----------------------+----------------------------------------------------
 Reporter:  scottmc    |       Owner:  axeld         
     Type:  bug        |      Status:  new           
 Priority:  normal     |   Milestone:  R1            
Component:  - General  |     Version:  R1 development
Blockedby:             |    Platform:  All           
 Blocking:             |  
-----------------------+----------------------------------------------------
 Perhaps related to #3028? Python regression test test_fileio.py fails :
 {{{
 ~/develop/python/Lib/test&gt; python test_fileio.py
 testAttributes (__main__.AutoFileTests) ... ok
 testErrors (__main__.AutoFileTests) ... ok
 testMethods (__main__.AutoFileTests) ... ok
 testOpendir (__main__.AutoFileTests) ... ok
 testReadinto (__main__.AutoFileTests) ... ok
 testRepr (__main__.AutoFileTests) ... ok
 testSeekTell (__main__.AutoFileTests) ... ok
 testWeakRefs (__main__.AutoFileTests) ... ok
 testAbles (__main__.OtherFileTests) ... FAIL
 testAppend (__main__.OtherFileTests) ... ok
 testBadModeArgument (__main__.OtherFileTests) ... ok
 testInvalidFd (__main__.OtherFileTests) ... ok
 testInvalidInit (__main__.OtherFileTests) ... ok
 testModeStrings (__main__.OtherFileTests) ... ok
 testTruncateOnWindows (__main__.OtherFileTests) ... ok
 testUnicodeOpen (__main__.OtherFileTests) ... ok
 testWarnings (__main__.OtherFileTests) ... ok

 ======================================================================
 FAIL: testAbles (__main__.OtherFileTests)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File &quot;test_fileio.py&quot;, line 156, in testAbles
     self.assertEquals(f.seekable(), False)
 AssertionError: True != False

 ----------------------------------------------------------------------
 Ran 17 tests in 0.157s

 FAILED (failures=1)
 Traceback (most recent call last):
   File &quot;test_fileio.py&quot;, line 268, in &lt;module&gt;
     test_main()
   File &quot;test_fileio.py&quot;, line 262, in test_main
     run_unittest(AutoFileTests, OtherFileTests)
   File &quot;/boot/common/lib/python2.7/test/test_support.py&quot;, line 710, in
 run_unittest
     _run_suite(suite)
   File &quot;/boot/common/lib/python2.7/test/test_support.py&quot;, line 693, in
 _run_suite
     raise TestFailed(err)
 test.test_support.TestFailed: Traceback (most recent call last):
   File &quot;test_fileio.py&quot;, line 156, in testAbles
     self.assertEquals(f.seekable(), False)
 AssertionError: True != False

 ~/develop/python/Lib/test&gt;
 }}}

-- 
Ticket URL: &lt;<A HREF="http://dev.haiku-os.org/ticket/3354">http://dev.haiku-os.org/ticket/3354</A>&gt;
Haiku &lt;<A HREF="http://dev.haiku-os.org">http://dev.haiku-os.org</A>&gt;
The Haiku operating system.

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="013909.html">[Haiku-bugs] [Haiku] #3353: resource.h broken (not implemented yet?)
</A></li>
	<LI>Next message: <A HREF="013911.html">[Haiku-bugs] [Haiku] #3355: using mv to move a folder onto itself	should fail
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13910">[ date ]</a>
              <a href="thread.html#13910">[ thread ]</a>
              <a href="subject.html#13910">[ subject ]</a>
              <a href="author.html#13910">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/haiku-bugs">More information about the Haiku-bugs
mailing list</a><br>
</body></html>
